# Site settings
title: building_sync
email: nicholas.long@nrel.gov
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://buildingsync.net"
twitter_username: nllong
github_username:  nllong

gems:
  - jekyll-redirect-from

# Build settings
markdown: kramdown
